version: '3.8'
services:
  sandbox:
    build:
      context: ./sandbox
    restart: always

  # Next.js Dashboard mock
  dashboard:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./dashboard:/app
    command: npm run dev
    ports:
      - "3000:3000"
